# Generated by Django 5.1.3 on 2024-11-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=20)),
                ("value", models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=100)),
                ("purchased_amount", models.IntegerField(default=0)),
                ("purchased_status", models.CharField(blank=True, max_length=50)),
                ("request_data", models.DateField()),
                ("company_code", models.CharField(max_length=20, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "market_cap",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor",
                        to="stocks.marketcap",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("five_days", models.FloatField(blank=True, default=0.0)),
                ("one_month", models.FloatField(blank=True, default=0.0)),
                ("three_months", models.FloatField(blank=True, default=0.0)),
                ("year_to_date", models.FloatField(blank=True, default=0.0)),
                ("one_year", models.FloatField(blank=True, default=0.0)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_value", models.FloatField(blank=True, default=0.0)),
                ("high", models.FloatField(blank=True, default=0.0)),
                ("low", models.FloatField(blank=True, default=0.0)),
                ("close", models.FloatField(blank=True, default=0.0)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_values",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
    ]
