# Generated by Django 5.1.3 on 2024-11-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="request_data",
            field=models.DateField(blank=True, null=True),
        ),
    ]
